name: marp
concurrency: marp

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Ensure docs dir exists
        run: mkdir -p docs
      - name: Marp Build (HTML)
        uses: docker://marpteam/marp-cli:v3.2.0
        with:
          args: README.md -o docs/index.html
        env:
          MARP_USER: root:root
      - name: Marp Build (README.pdf)
        uses: docker://marpteam/marp-cli:v3.2.0
        with:
          args: README.md --allow-local-files --pdf -o docs/k6-oh-99.pdf
        env:
          MARP_USER: root:root
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "docs"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
